# ================= EXECUTION CONFIG =================
#testExecutionMode=docker
testExecutionMode=local
browser=chrome
headless=true

# ================= ENVIRONMENT CONFIG =================
applicationEnvironment=live
#applicationEnvironment=local

# ================= APPLICATION URLS =================
localUrl=http://localhost/OrangeHRM/orangehrm-5.8/web/index.php/auth/login

dockerLocalUrl=http://host.docker.internal/OrangeHRM/orangehrm-5.8/web/index.php/auth/login

liveUrl=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login


# ================= SELENIUM GRID =================
gridUrl=http://localhost:4444/wd/hub


# ================= WAITS =================
implicitWait=50
explicitWait=60
staticWait=500



# ================= TEST DATA =================
username=Admin
password=admin123