#url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
url=http://localhost/OrangeHRM/orangehrm-5.8/web/index.php/auth/login
#ongeDatabaseURL=http://localhost/phpmyadmin/index.php?route=/table/sql&db=orangehrm&table=hs_hr_employee
#ongeDatabaseURL USER=root password=nill
browser=chrome
implicitWail=50
staticWait=500
explicitWait=60
username=admin
password=Manish@880