name: Selenium-TestNG Framework

on:
  push:
    branches: [ "manish" ]

  pull_request:
    branches: [ "manish" ]

jobs:
  selenium-tests:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        browser: [chrome, firefox, edge]

    permissions:
      contents: read
      checks: write
      issues: write

    steps:

    - name: Checkout Project
      uses: actions/checkout@v4

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Chrome
    - name: Setup Chrome
      if: matrix.browser == 'chrome'
      uses: browser-actions/setup-chrome@v1

    # Firefox
    - name: Setup Firefox
      if: matrix.browser == 'firefox'
      uses: browser-actions/setup-firefox@v1

    # Edge
    - name: Setup Edge
      if: matrix.browser == 'edge'
      uses: browser-actions/setup-edge@v1

    - name: Verify Browser
      run: |
        if [ "${{ matrix.browser }}" = "chrome" ]; then
          google-chrome --version
        elif [ "${{ matrix.browser }}" = "firefox" ]; then
          firefox --version
        else
          microsoft-edge --version
        fi

    - name: Build Project
      run: mvn clean install -DskipTests

    - name: Execute Selenium Tests
      run: mvn test -Dbrowser=${{ matrix.browser }}

    # Upload Logs
    - name: Upload Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Logs-${{ matrix.browser }}
        path: logs/

    # Upload Extent Reports
    - name: Upload Extent Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ExtentReports-${{ matrix.browser }}
        path: extentReports/

    # Upload TestNG Reports
    - name: Upload TestNG Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: TestNG-Output-${{ matrix.browser }}
        path: test-output/

    # Publish Test Results
    - name: Publish Test Report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: Selenium TestNG Results - ${{ matrix.browser }}
        path: target/surefire-reports/junitreports/TEST-*.xml
        reporter: java-junit
